#!/usr/bin/env bash

: '
Copyright (c) Meta Platforms, Inc. and affiliates., Inc. All rights reserved.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

yarn node "$DIR"/packages/jest-cli/bin/jest "$@"



# alipays://platformapi/startapp?appId=2019090366858381&page=pages/home/index&query=initialScene=alipay_traveltab_jgw
# alipays://platformapi/startapp?appId=2019090366858381&page=pages/home/index&query=initialScene%3Dalipay_traveltab_jgw
# alipays%3A%2F%2Fplatformapi%2Fstartapp%3FappId%3D2019090366858381%26page%3Dpages%2Fhome%2Findex%26query%3DinitialScene%253Dalipay_traveltab_jgw


# https://ds.alipay.com/?scheme=alipays%3A%2F%2Fplatformapi%2Fstartapp%3FappId%3D2019090366858381%26page%3Dpages%2Fhome%2Findex%26query%3DinitialScene%253Dalipay_traveltab_jgw